name: test

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  check_author:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check PR Author Membership
        run: |
          echo ${{ github.actor }}
