name: Label community PRs

on:
  schedule:
    - cron: '*/1 * * * *'

permissions: write-all

jobs:
  check_author:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check PR Author Membership
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e
          for id in `gh pr list -S 'draft:false' -s 'open'|awk '{print $1}'`
          do
            name=`gh pr view $id --json author -q '.author.login'`
            #gh api orgs/Kong/members --paginate -q '.[].login'|grep -q "^${name}$"
            #if [ $? -ne 0 ]; then
              #gh pr edit $id --add-label "author/community"
              gh pr edit $id --add-label "bug"
            #fi
          done
