name: Label community PRs

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  check_author:
    runs-on: ubuntu-latest

    steps:
      - name: Add Label if Author is not a member
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e
          gh pr edit ${{ github.event.pull_request.html_url }} --add-label "bug"
