name: main

on:
  schedule:
    - cron: '*/1 * * * *'

permissions:
  actions: write

jobs:
  check_author:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check PR Author Membership
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "aaa"
